ngram_tfidf_params:
  NGRAM_RANGE : (1, 2)
  NORM : "l2"
  SUBLINER_TF : True
  test_size: 0.25
  random_state : 42


Random_Forest:
  n_estimators : 1000
  max_depth : 12


Logistic_Regression:
  C : 2
  max_iter : 1000
  n_jobs : -1

VotingClassifier:
    voting : 'soft'
    weights : [1,2,3,4]

svc:
  probability: True