artifacts_root: artifacts


data_ingestion:
  root_dir: artifacts/data_ingestion
  subtopics_dict: Synthetic_data/subjects_subtopics_dict (1).json
  local_data_file: artifacts/data_ingestion/data.csv
  sentences_dict: artifacts/data_ingestion/sentences_dict.json
  sample_num: 90


# prepare_base_model:
#   root_dir: artifacts/prepare_base_model
#   base_model_path: artifacts/prepare_base_model/base_model.h5
#   updated_base_model_path: artifacts/prepare_base_model/base_model_updated.h5



# prepare_callbacks:
#   root_dir: artifacts/prepare_callbacks
#   tensorboard_root_log_dir: artifacts/prepare_callbacks/tensorboard_log_dir
#   checkpoint_model_filepath: artifacts/prepare_callbacks/checkpoint_dir/model.h5




training:
  root_dir: artifacts/training
  trained_model_path: artifacts/training/ensemble_model.pkl
  n_gram_tfidf_model: artifacts/training/n_gram_tfidf_model.pkl
  train_data: artifacts/training/test_data
  eval_data: artifacts/training/eval_data
  
