artifacts_root: artifacts


data_ingestion:
  root_dir: artifacts/data_ingestion
  subtopics_dict: Synthetic_data/subjects_subtopics_dict (1).json
  local_data_file: artifacts/demo/demo.csv # artifacts/data_ingestion/17k_synthetic_data (1).csv
  sentences_dict: artifacts/demo/demo.json  # artifacts/data_ingestion/sentences_dict.json
  sample_num: 80 #numer of sample


# prepare_base_model:
#   root_dir: artifacts/prepare_base_model
#   base_model_path: artifacts/prepare_base_model/base_model.h5
#   updated_base_model_path: artifacts/prepare_base_model/base_model_updated.h5
prepare_finetune_model:
  root_dir: artifacts/prepare_finetune_model
  fintune_model_path: artifacts/prepare_finetune_model/unsloth.Q4_K_M.gguf
  model_repo: 05deepak/subject_classifeir_lora_modelv3_GGuf_Q_4
  model_filename : unsloth.Q4_K_M.gguf


# prepare_callbacks:
#   root_dir: artifacts/prepare_callbacks
#   tensorboard_root_log_dir: artifacts/prepare_callbacks/tensorboard_log_dir
#   checkpoint_model_filepath: artifacts/prepare_callbacks/checkpoint_dir/model.h5



# remove comments line for running and craeting the artifacts
training:
  root_dir:  artifacts/demo # artifacts/training
  trained_model_path: artifacts/demo/ensemble_model.pkl # artifacts/training/ensemble_model.pkl
  n_gram_tfidf_model: artifacts/demo/n_gram_tfidf_model.pkl # artifacts/training/n_gram_tfidf_model.pkl
  train_data:  artifacts/demo/test_data # artifacts/training/test_data
  eval_data: artifacts/demo/eval_data # artifacts/training/eval_data
  
